### ISSUE TITLE
ImportError: DLL load failed while importing _pyllamacpp: A DLL initialization routine failed.

### ISSUE THREAD

**Issue by BlueSchnabeltier** [thomasantony/llamacpp-python#17]
How to fix?

Heres the log:
```Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\GPT4All\main.py", line 1, in <module>
    from pyllamacpp.model import Model
  File "C:\Users\User\PycharmProjects\GPT4All\venv\lib\site-packages\pyllamacpp\model.py", line 21, in <module>
    import _pyllamacpp as pp
ImportError: DLL load failed while importing _pyllamacpp: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.```

**Comment by thomasantony** [comment]
I think you are on the wrong repository. This might be what you are looking for: https://github.com/nomic-ai/pyllamacpp
