### ISSUE TITLE
AttributeError: module 'llamacpp' has no attribute 'llama_model_quantize'

### ISSUE THREAD

**Issue by rpfilomeno** [thomasantony/llamacpp-python#19]
Running on pwindows 11, installed via pip

❯ pip install llamacpp --pre
Collecting llamacpp
  Using cached llamacpp-0.1.13-cp310-cp310-win_amd64.whl (190 kB)
Installing collected packages: llamacpp
Successfully installed llamacpp-0.1.13
. . .
❯ llamacpp-convert .\models\7B\ 1
. . .
❯ llamacpp-quantize .\models\7B\
Quantizing model in .\models\7B\ to q4_0
Quantizing file: ggml-model-f16.bin to ggml-model-q4_0.bin
Traceback (most recent call last):
  File "C:\Users\Roger\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Roger\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Roger\Documents\Github\vtuberbot\venv\Scripts\llamacpp-quantize.exe\__main__.py", line 7, in <module>
  File "C:\Users\Roger\Documents\Github\vtuberbot\venv\lib\site-packages\llamacpp\quantize.py", line 45, in main
    llamacpp.llama_model_quantize(os.path.join(root, file), os.path.join(root, output_file), q_type)
AttributeError: module 'llamacpp' has no attribute 'llama_model_quantize'

**Comment by thomasantony** [comment]
I am able to reproduce this. Will fix it in the next release.

**Comment by thomasantony** [comment]
Fixed in [0.1.14](https://github.com/thomasantony/llamacpp-python/releases/tag/v0.1.14)
