### ISSUE TITLE
problem with llama-convert 

### ISSUE THREAD

**Issue by ShudoBlon** [thomasantony/llamacpp-python#7]
hi, when i do `llamacpp-convert .model/7B/ 1` it return this to me : 

`Traceback (most recent call last):
  File "/home/ajimenez/.local/bin/llamacpp-convert", line 8, in <module>
    sys.exit(main())
  File "/home/ajimenez/.local/lib/python3.10/site-packages/llamacpp/convert.py", line 80, in main
    tokenizer = SentencePieceProcessor(fname_tokenizer)
  File "/home/ajimenez/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/ajimenez/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/ajimenez/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
`

can you help me ?

**Comment by thomasantony** [comment]
Which version of `llamacpp` are you running?

**Comment by thomasantony** [comment]
Your tokenizer model file may be corrupted. Can you compute a checksum for it? 

`sha256sum models/tokenizer.model`

This is what I have:
```
9e556afd44213b6bd1be2b850ebbbd98f5481437a8021afaf58ee7fb1818d347  ./models/tokenizer.model
```
